<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.delete.8bc2c0f9-b1cf-4a72-854f_3b8889</name>
   <tag></tag>
   <elementGuidId>4817cd9d-d702-4869-a687-662eeb6c2f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.delete.8bc2c0f9-b1cf-4a72-854f-677af00e11a7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.delete.8bc2c0f9-b1cf-4a72-854f-677af00e11a7&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88b44178-37c6-45eb-9322-305e27d2799a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.delete.8bc2c0f9-b1cf-4a72-854f-677af00e11a7</value>
      <webElementGuid>9bfac5bc-99b5-440f-98fd-5be26d011ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>b2917fcf-13b6-4d3e-9221-2cc888df100e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>3ea54cab-4ffb-4a91-838d-438a71c1561e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delete Chemistry Made Easy: An Illustrated Study Guide For Students To Easily Learn Chemistry</value>
      <webElementGuid>02e17bde-a969-4427-9af3-0dc8c1dbcbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0fe50465-33ee-407a-bfbe-c0b7fa7d3c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-link</value>
      <webElementGuid>fe985716-7ad9-4d1f-8cac-cc6dd1e18880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-8bc2c0f9-b1cf-4a72-854f-677af00e11a7&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;sc-item-content-group&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;a-size-small sc-action-delete&quot;]/span[@class=&quot;a-declarative&quot;]/input[@class=&quot;a-color-link&quot;]</value>
      <webElementGuid>1aea5303-6a04-4689-b865-3107da1fd553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.delete.8bc2c0f9-b1cf-4a72-854f-677af00e11a7']</value>
      <webElementGuid>62c8a816-bb7b-4556-8315-0b09d17ce089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-8bc2c0f9-b1cf-4a72-854f-677af00e11a7']/div[4]/div/div[2]/div/span[2]/span/input</value>
      <webElementGuid>5777f48d-51db-4f60-a747-ef52ba0879d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>10e21f46-b628-4afc-883a-016a58aa9d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.delete.8bc2c0f9-b1cf-4a72-854f-677af00e11a7' and @type = 'submit']</value>
      <webElementGuid>8c0b7415-ff33-474f-b9be-5e53eb5714ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
